### ISSUE TITLE
Couldn't load plugin 'processing-tandem-master' due to error when calling classFactory() method

### ISSUE THREAD

**Issue by Robotuner** [alexbruy/processing-taudem#18]
The rest of the message is below.  QGIS 3.18  Is Taudem even compatible with python 3.8?

Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/lkong/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing-taudem-master\__init__.py", line 52, in classFactory
    from TauDEMProviderPlugin import TauDEMProviderPlugin
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'TauDEMProviderPlugin'

**Comment by alexbruy** [comment]
Seems the plugin was installed incorrectly.
